### ISSUE TITLE
Braden Everson, I need a backend developer for a project

### ISSUE THREAD

**Issue by Prottoy2938** [BradenEverson/Agronomous#1]
I'm thinking of expanding [Ingredient](https://ingredient.now.sh/) project. Recently the application got some pretty good feedback.
And it would be great if I have someone who could manage the backend and work on it. 

Would you like to join?  It would be a long term project

Currently, I've working on Recipe Filter Feature

I don't have your email

**Comment by BradenEverson** [comment]
Hey Prottoy, my email's bradeneverson@gmail.com, currently I'm working on this project but afterwards I think I'd be able to help

**Comment by Prottoy2938** [comment]
I've created a new team on slack and sent you an invite. If you have free
time you can send me a message there.

 I would show you around, tell you about the project and discuss from where
you should start developing

If you haven't already received slack the invite, send me a reply
